(defalias 'qrr 'query-replace-regexp)
(defalias 'lml 'list-matching-lines)
(defalias 'dml 'delete-matching-lines)
(defalias 'dnml 'delete-non-matching-lines)
(defalias 'dtw 'delete-trailing-whitespace)
(defalias 'sl 'sort-lines)
(defalias 'rr 'reverse-region)
(defalias 'rs 'replace-string)

(defalias 'fd 'find-dired)
(defalias 'ees 'eshell)
(defalias 'here 'Open)
(defalias 'rof 'recentf-open-files)
(defalias 'rc 'xah-run-current-file)
(defalias 'Calc 'helm-calcul-expression)
(defalias 'Marks 'helm-all-mark-rings) ; can't use marks , taken by evil-mode
(defalias 'Grep 'helm-occur) ; interactive grep in current buffer
(defalias 'inbox 'open-my-inbox)
(defalias 'todo 'open-my-todo-list)
(defalias 'keys 'my-key-binds)
(defalias 'note 'open-notes-dir)
